version: "3.6"

services:

  # Nginx
  nginx:
    restart: always
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "8080:8080"

  # Albert Services
  albert_ui:
    restart: always
    build:
      context: ./albert_ui
      target: development
    depends_on:
      - nginx
      - albert_api
    entrypoint:
      - yarn
      - start
    volumes:
      - ./albert_ui:/home/node/src
      - /home/node/src/node_modules
  albert_api:
    build:
      context: ./albert_api
      target: development
    restart: always
    depends_on:
      - nginx
    environment:
      FLASK_ENV: development
    entrypoint:
      - poetry
      - run
      - flask
      - run
      - --host=0.0.0.0
  albert_db:
    build: ./albert_db
    restart: always
    environment:
      MYSQL_DATABASE: albert_db
      MYSQL_USER: albert
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    volumes:
      - ./albert_db/mysql:/var/lib/mysql

  # Boa Services
  boa_ui:
    build: ./boa_ui
  boa_resource_api:
    build: ./boa_resource_api
  boa_resource_db:
    build: ./boa_resource_db
  boa_auth_api:
    build: ./boa_auth_api
  boa_auth_db:
    build: ./boa_auth_db
